### ISSUE TITLE
Fixed Gain command inconsistencies between TIVA firmware versions

### ISSUE THREAD

**Issue by Seoras** [InnoSpectra/ISC_NIRScan_Tiva_FW#1]
We are seeing inconsistent behaviour between TIVA firmware version in being able to set a fixed gain value for the purpose of performing calibration measurements.

In version 2.1.0.67 and also in 2.1.2 we are able to set the gain to 64 using the command sequence that was defined by Texas Instruments at Sagitto's request:

```
byte 1 0x04
byte 2 0x0c
byte 3 0x03 (CMD1_WRITE)
byte 4 [0x02] (length)
byte 5 [0x00/0x01] (boolean)
byte 6 [0x(GAIN VALUE)]
```

This is the command sequence that we have always used and it has worked flawlessly until now.
If we try to set the gain to 32,16,8,4 or 1 it fails as the reported gain, post scan, is always 64.

We found version 2.1.0.69 on your website and discovered that it would allow us to set the gain to any value using a modified and shortened version of this command:

```
byte 1 0x04
byte 2 0x0c
byte 3 0x03 (CMD1_WRITE)
byte 4 [0x01] (length)
byte 5 [0x(GAIN VALUE)]
```

In version 2.1.2 we have tried both the original 6 byte command and the modified 5 byte command.
Both seem to work but will only allow us to set the gain to 64.
This makes me think that there has been a failure and that gain=64 is just the default setting when the gain write command fails.

We are confused as to what method is correct since there are inconsistencies between TIVA firmware versions 2.1.0.67, 2.1.0.69 & 2.1.2

1. Which is the correct command sequence ?
2. Why does neither command sequence work for anything other than gain=64 for the latest firmware version (2.1.2) ?

**Comment by JeremyHsieh** [comment]
Originally the setting was 6 bytes, we changed it to 5 bytes and created dedicated Bluetooth command for Set Scan PGA (0x43484146-444C-5020-4E49-52204E616E6F) since Tiva version 2.1.0.52.

This allow user to send one byte for PGA through this characteristic to control the automatic and fixed gains. Value "0" is set for automatic gain control and "1,2,4,8,16,32,64" for fixed gain.

This change also has influence to setting the gain through "Internal Command Service".

Please see the updated Bluetooth command sets document for the new API's.

Also, you need to get your device activated for these new functions, please check with our Salesman for it.

Later, the device manufactured from our factory will be pre-activated and you will not need to set it again when you revieve the new devices. 
 
[ISC NIRScan Bluetooth Communications Data Sheet V1.3 - 20190610JH.pdf](https://github.com/InnoSpectra/ISC_NIRScan_Tiva_FW/files/3406030/ISC.NIRScan.Bluetooth.Communications.Data.Sheet.V1.3.-.20190610JH.pdf)

**Comment by JeremyHsieh** [comment]
If your devices were not activated for those new functions, the API returns false and perform as automatic gain control. That's why you always got PGA 64 after scan.
